@echo off
:: --------------------------------------------------------------------------- ::
:: applications\common.bat - Shared targets (build, clean, install)            ::
:: --------------------------------------------------------------------------- ::

:: If no target is provided, default to 'all' (clean then build)
set "TARGET=%~1"
if "%TARGET%"=="" set "TARGET=all"

:: Route to the correct label
if /I "%TARGET%"=="all" goto :all
if /I "%TARGET%"=="build" goto :build
if /I "%TARGET%"=="install" goto :install
if /I "%TARGET%"=="clean" goto :clean
if /I "%TARGET%"=="uninstall" goto :uninstall

echo Error: Unknown target '%TARGET%'
exit /b 1

:: =========================================================================== ::
:: TARGET IMPLEMENTATIONS                                                      ::
:: =========================================================================== ::

:all
call :clean
call :build
exit /b %errorlevel%

:build
if exist "%HERMITELBM_INCLUDE_DIR%\hardware.bat" (
    call "%HERMITELBM_INCLUDE_DIR%\hardware.bat"
)
echo %NVCXX% %NVCXX_FLAGS% %SOURCE% -o %EXECUTABLE%
%NVCXX% %NVCXX_FLAGS% %SOURCE% -o %EXECUTABLE% >"%TEMP%\nvcc_%EXECUTABLE%.log" 2>&1
if errorlevel 1 (
    type "%TEMP%\nvcc_%EXECUTABLE%.log"
    del "%TEMP%\nvcc_%EXECUTABLE%.log"
    exit /b %errorlevel%
)
del "%TEMP%\nvcc_%EXECUTABLE%.log"
exit /b 0

:install
call :clean
call :uninstall
call :build
if %errorlevel% neq 0 exit /b %errorlevel%

if not exist "%HERMITELBM_BIN_DIR%" mkdir "%HERMITELBM_BIN_DIR%"
copy /Y "%EXECUTABLE%" "%HERMITELBM_BIN_DIR%\%EXECUTABLE%" >nul
del /F /Q "%EXECUTABLE%"
exit /b 0

:clean
if exist "%EXECUTABLE%" (
    del /F /Q "%EXECUTABLE%"
)
:: Clean up MSVC artifacts generated by nvcc (like .exp or .lib files)
if exist "%EXECUTABLE:~0,-4%.exp" del /F /Q "%EXECUTABLE:~0,-4%.exp"
if exist "%EXECUTABLE:~0,-4%.lib" del /F /Q "%EXECUTABLE:~0,-4%.lib"
exit /b 0

:uninstall
if exist "%HERMITELBM_BIN_DIR%\%EXECUTABLE%" (
    del /F /Q "%HERMITELBM_BIN_DIR%\%EXECUTABLE%"
)
exit /b 0