# --------------------------------------------------------------------------- #
#                                                                             #
#  HermiteLBM: CUDA-based moment representation Lattice Boltzmann Method      #
#  Developed at UDESC - State University of Santa Catarina                    #
#  Website: https://www.udesc.br                                              #
#  Github: https://github.com/Geoenergia-Lab/HermiteLBM                       #
#                                                                             #
# --------------------------------------------------------------------------- #

include $(HERMITELBM_PROJECT_DIR)/common.mk

EXECUTABLE = computeVersion
SOURCE = computeVersion.cu

include $(HERMITELBM_PROJECT_DIR)/applications/common.mk

# --------------------------------------------------------------------------- #